# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_sharing.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'file_sharing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ile_sharing.proto\x12\x0b\x66ilesharing\"1\n\x0bUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"0\n\x0c\x41uthResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"B\n\x0b\x46ileRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"0\n\x0c\x46ileResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2R\n\x0b\x41uthService\x12\x43\n\x0c\x41uthenticate\x12\x18.filesharing.UserRequest\x1a\x19.filesharing.AuthResponse2\x9c\x01\n\x12\x46ileStorageService\x12\x41\n\nUploadFile\x12\x18.filesharing.FileRequest\x1a\x19.filesharing.FileResponse\x12\x43\n\x0c\x44ownloadFile\x12\x18.filesharing.FileRequest\x1a\x19.filesharing.FileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_sharing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=35
  _globals['_USERREQUEST']._serialized_end=84
  _globals['_AUTHRESPONSE']._serialized_start=86
  _globals['_AUTHRESPONSE']._serialized_end=134
  _globals['_FILEREQUEST']._serialized_start=136
  _globals['_FILEREQUEST']._serialized_end=202
  _globals['_FILERESPONSE']._serialized_start=204
  _globals['_FILERESPONSE']._serialized_end=252
  _globals['_AUTHSERVICE']._serialized_start=254
  _globals['_AUTHSERVICE']._serialized_end=336
  _globals['_FILESTORAGESERVICE']._serialized_start=339
  _globals['_FILESTORAGESERVICE']._serialized_end=495
# @@protoc_insertion_point(module_scope)
